- hosts: localhost
  connection: local
- hosts: images
  gather_facts: false
  vars:
    nodename: "{{ inventory_hostname }}"
    dnsname: "{{ inventory_hostname }}"
    ansible_ssh_user: "{{ user }}"
    ansible_sudo_pass: "{{ pass }}"
    ansible_ssh_private_key_file: "{{ key }}"
  tasks:
  - local_action: shell azure vm image list --json | jq '[.[] | select(.label == "{{ image_label }}")] | sort_by("publishedDate")[-1:] | .[].name' -r
    register: image_res
  - set_fact:
      image: "{{ image_res.stdout }}"
      nodeimage: "{{ image_res.stdout }}"
  - include: tasks/create.yml
  - include: tasks/wait.yml
  - include: tasks/load.yml
  - { include: tasks/setup.yml, sudo: true }
  - { include: tasks/capture.yml }
  - { include: tasks/remove_service.yml }
