- hosts: images
  gather_facts: false
  vars:
    nodename: "{{ inventory_hostname }}-test"
    nodeimage: "{{ inventory_hostname }}"
    ansible_ssh_user: "{{ user }}"
    ansible_sudo_pass: "{{ pass }}"
    ansible_ssh_private_key_file: "{{ key }}"
  tasks:
  - include: tasks/create.yml
  - include: tasks/wait.yml
  - include: tasks/load.yml
  - { include: tasks/test.yml, sudo: true }
