- hosts: images
#  gather_facts: false
  connection: local
  tasks:
  - local_action: add_host
                  name="{{ inventory_hostname }}-node{{ item }}"
                  image="{{ inventory_hostname }}"
                  groups=cluster
                  ansible_ssh_port=220{{ item }}
                  #nodeimage="{{ inventory_hostname }}"
                  #nodename="{{ inventory_hostname }}-node{{ item }}"
                  #dnsname="{{ inventory_hostname }}-cluster"
                  #ansible_ssh_user="{{ user }}"
                  #ansible_sudo_pass="{{ pass }}"
                  #ansible_ssh_private_key_file="{{ key }}"
    with_sequence: count={{ cluster_size }}
#  - { include: tasks/create_service.yml, dnsname: "{{ inventory_hostname }}-cluster" }

- hosts: cluster
  connection: local
  tasks:
  - set_fact:
      nodeimage: "{{ image }}"
      dnsname: "{{ image }}-cluster"
      nodename: "{{ inventory_hostname }}"
      ansible_ssh_user: "{{ user }}"
      ansible_sudo_pass: "{{ pass }}"
      ansible_ssh_private_key_file: "{{ key }}"
 
- hosts: cluster
  connection: local
  serial: 1
  tasks:
  - include: tasks/create.yml

- hosts: cluster
  connection: local
  tasks:
  - include: tasks/wait.yml

- hosts: cluster
  tasks:
  - include: tasks/load.yml
  - { include: tasks/test.yml, sudo: true }
