- hosts: images
  connection: local
  tasks:
  - command: azure vm create --location "{{ location }}" --ssh --ssh-cert {{ ansible_ssh_private_key_file }} -n {{ inventory_hostname }}-test {{ inventory_hostname }}-test {{ inventory_hostname }} {{ ansible_ssh_user }} {{ ansible_sudo_pass }}

- hosts: images
  connection: local
  tasks:
  - action: shell azure vm show {{ inventory_hostname }}-test --json | jq -r '.InstanceStatus'
    register: vm_show
    until: vm_show.stdout == "ReadyRole" or vm_show.stdout == "Failed"
    failed_when: vm_show.stdout == "Failed"
    retries: 15
    delay: 60
  - action: shell azure vm show {{ inventory_hostname }}-test --json > ./json/{{ inventory_hostname }}-test.json

- hosts: images
  sudo: True
  #connection: local
  vars:
    azure: "{{ lookup('file', 'json/' + inventory_hostname + '-test.json') }}"
    ansible_ssh_host: "{{ azure['Network']['Endpoints'][0]['Vip'] }}"
    ansible_ssh_port: "{{ azure['Network']['Endpoints'][0]['Port'] }}"
  tasks:
  - { include: tasks/test.yml }
