- hosts: images
  connection: local
  tasks:
  - command: azure vm image delete -q -b {{ inventory_hostname }}-test
    ignore_errors: true
  - command: azure vm delete -q -b {{ inventory_hostname }}-test
    ignore_errors: true
