- lineinfile: dest=/etc/sudoers regexp='^Defaults:root' line='Defaults:root !requiretty'

- copy: src=limits.conf dest=/etc/security/limits.d/90-nofile-riak.conf owner=root group=root
#- copy: src=riak-app.config dest=/etc/riak/app.config owner=root group=root
#- copy: src=riak-vm.args dest=/etc/riak/vm.args owner=root group=root
- copy: src=riak-riak.conf dest=/etc/riak/riak.conf owner=riak group=riak
- copy: src=firstboot dest=/usr/sbin/firstboot mode=0755 owner=root group=root
- copy: src=waagent.conf dest=/etc/waagent.conf owner=root group=root

- command: df -T /var/lib/riak
  register: df

- mount: "name={{ df.stdout_lines[-1].split(' ')[5] }} src={{ df.stdout_lines[-1].split(' ')[1] }} fstype={{ df.stdout_lines[-1].split(' ')[2] }} opts=noatime state=present"

- sysctl: name="{{ item }}" state=absent reload=no
  with_items:
  - net.bridge.bridge-nf-call-ip6tables
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-arptables

- sysctl: name="{{ item.name }}" value="{{ item.value }}" sysctl_set=yes state=present reload=yes
  with_items:
  - { name: vm.dirty_bytes, value: 209715200 }
  - { name: vm.dirty_background_bytes, value: 104857600 }
  - { name: vm.dirty_writeback_centisecs, value: 200 }
  - { name: vm.dirty_expire_centisecs, value: 200 }
  - { name: net.ipv4.tcp_max_syn_backlog, value: 40000 }
  - { name: net.core.somaxconn, value: 40000 }
  - { name: net.ipv4.tcp_sack, value: 1 }
  - { name: net.ipv4.tcp_window_scaling, value: 1 }
  - { name: net.ipv4.tcp_fin_timeout, value: 15 }
  - { name: net.ipv4.tcp_keepalive_intvl, value: 30 }
  - { name: net.ipv4.tcp_tw_reuse, value: 1 }
  - { name: net.ipv4.tcp_moderate_rcvbuf, value: 1 }
  - { name: vm.swappiness, value: 0 }
