- local_action: command azure vm create --location "{{ location }}" --ssh --ssh-cert {{ key }} -n {{ nodename }} {{ nodename }} {{ nodeimage }} {{ user }} {{ pass }}
  register: vm_create
  until: vm_create.rc == 0
  retries: 3
  delay: 5
